// Generated by https://quicktype.io

export interface Person {
  totalPassengers: number | undefined;
  totalPages: number | undefined;
  data: Datum[];
}

export interface Datum {
  _id: string;
  name: string;
  trips: number;
  airline: Airline[];
  __v: number;
}

export interface Airline {
  id: number;
  name: string;
  country: string;
  logo: string;
  slogan: string;
  head_quaters: string;
  website: string;
  established: string;
}
